### ISSUE TITLE
Get Github benefits for the org

### ISSUE THREAD

**Issue by palash25** [p-society/goals#12]
I'm currently enrolled in the Github campus expert training. If my application is accepted we will be able to get the following benefits for our org

**The repo is private so I will  just quote from their docs**

```
- Access to funding in support of your open source club activities.
- An upgrade for your student Organization to a paid org, on the "Team" tier.
- Access to the GitHub Grant for your event!
- We'll send you printed cheat sheets and learning materials for your workshops.
```

**Comment by knrt10** [comment]
@palash25 page not found .

**Comment by palash25** [comment]
@knrt10 click on the link and you will find the page 
I think there is something wrong with the bot maybe it cannot unfurl annotated links you should raise an issue on probot

**Comment by palash25** [comment]
@knrt10 updated check it out

**Comment by Rupeshiya** [comment]
@palash25  page not found (404)

**Comment by knrt10** [comment]
@Rupeshiya 
>The repo is private so I will just quote from their docs
	- Access to funding in support of your open source club activities.
	- An upgrade for your student Organization to a paid org, on the "Team" tier.
	- Access to the GitHub Grant for your event!
	- We'll send you printed cheat sheets and learning materials for your workshops.

**Comment by Rupeshiya** [comment]
@knrt10  yep  😂

**Comment by palash25** [comment]
> @palash25 page not found (404)

My bad the repo I refrenced is private and only I have access to it which I forgot :sweat_smile:  @Rupeshiya

**Comment by palash25** [comment]
Done
