### ISSUE TITLE
Start a Node School chapter 

### ISSUE THREAD

**Issue by palash25** [p-society/goals#16]
I'm not sure whether we need this or not but it might be beneficial to start a conversation at least.

@knrt10 and @IamRaviTejaG would you two be interested in leading this effort and finding out more about it?

I guess Bhubaneswar doesn't have a chapter currently.

Important links:-

https://nodeschool.io/

https://nodeschool.io/chapters.html

https://nodeschool.io/about.html

<blockquote><img src="/favicon.ico" width="48" align="right"><div><strong><a href="https://nodeschool.io/">NodeSchool</a></strong></div></blockquote>
<blockquote><img src="/favicon.ico" width="48" align="right"><div><strong><a href="https://nodeschool.io/chapters.html">NodeSchool - Chapters</a></strong></div></blockquote>
<blockquote><img src="/favicon.ico" width="48" align="right"><div><strong><a href="https://nodeschool.io/about.html">NodeSchool - About</a></strong></div></blockquote>

**Comment by palash25** [comment]
ping @IamRaviTejaG @knrt10 can you guys look into this? whether it would be beneficial or not?

**Comment by knrt10** [comment]
Will depend on the participation of students.

**Comment by palash25** [comment]
> Will depend on the participation of students.

We can't predict that. What I meant was if we get participation would we benefit from having a node school chapter? If not then feel free to close this.

**Comment by IamRaviTejaG** [comment]
@knrt10 @palash25 Correct me if I'm wrong, but isn't Node just a framework for building a server, or is it more?! So, if it's just the former, having a chapter seems like an overkill to me, else, I'm fine with the school chapter. 😄

**Comment by knrt10** [comment]
Thats where you are wrong my friend, node is way beyond that. Anyway closing this issue as it won’t be of much use. So ☮️
