### ISSUE TITLE
Start CSI Chapter / Ideas to revive ACM chapter

### ISSUE THREAD

**Issue by palash25** [p-society/goals#18]
Not sure how much it would help but I have seen other colleges with a CSI chapter do well in terms of research. We might want to look into it.

cc @hdidwania @shivank01 @ayush1999

**Comment by shivank01** [comment]
@palash25 The fee to open the chapter is Rs.5000 .  Will college give this amount to open the chapter?

**Comment by ayush1999** [comment]
@shivank01 They should if we pressurize them. Seeing how Jena spends, I don't think 5000 would be a big amount for him.

**Comment by shivank01** [comment]
Okay, then we will try to open this chapter as it is really good.

**Comment by sr6033** [comment]
I had contacted the CSI bbsr head this semester. He was really willing to open up a chapter here. He also said that they will fund any events if we are organising and they find them to be quite good and helpful. I hadn't told u guys but this chapter is going to be opened next semester somehow.

**Comment by ankitjha97** [comment]
Why don't you people take over the ACM chapter.It will be a good platform too.You will be connected to student chapters across all over India and even organize competitions at All India Level.We didn't have a big team this session but you can have a look at ACM chapters of BITS Pilani and others.They have an impressive team.You can make a big team for upcoming sem and it is well funded by Placement Cell.?
http://bitsacm.acm.org/

**Comment by sr6033** [comment]
That too. Ankit and I was planning to have some of you in ACM and both these clubs should work together.

**Comment by ayush1999** [comment]
Sounds like a great idea. @ankitjha97 . What do think @shivank01 @hdidwania ?

**Comment by shivank01** [comment]
yeah great

**Comment by sr6033** [comment]
Also instead of opening up many chapters, focusing on the existing and making them more active will be better, i suppose.

**Comment by ankitjha97** [comment]
Look, there are many competitions organized at All India Level among the ACM chapters and they award the best ACM chapters.If we have a good team, then we can surely make a mark and get known which can attract a lot of attention to our college.Last year ACM Bits Pilani won the prestigious award for best ACM.This year, if you have a strong, then you will surely win this award.

**Comment by palash25** [comment]
@ankitjha97 I saw the BITS-ACM site and the events that they conduct. Its something that we could do too.

@sr6033 is right about reviving existing chapters but even if we have multiple chapters two or more chapters can work in tandem to conduct events that way all the chapter will have activities to showcase on their websites and none of them will go dormant. We can also organize a few programming society events in association with our ACM chapter.

If we could set up Papers We Love #17 chapter we can have talks & discussion about research papers under that chapter and these will be organized by ACM chapter

I also saw that the folks at BITS conduct quizess as one of their sessions and as far as I know quizerrati is an independent group right know if the quizerratis can organize tech quizess under the ACM banner with would have another event to add to ACM's activity. Maybe quizerrati can be a SIG under ACM related issue #8 
cc @nawedx your thoughts on this

Their flagship event were talks by experienced software devs and researchers I'm not sure we currently have the resources to organize large scale talks or not but this can be doable if we can get an OWASP chapter (they provide a funding of $500-$1000 for events iirc and can also contact security experts to deliver a talk) 
Related issue #6 

This way we might be able to have the best of both worlds i.e. existing chapters stay active and new chapters bring in their benefits and add to our activities as a community.

Just one question do we have an ACM website? If yes then can you give me a link. Maybe a redesign of the ACM website can also be a good project.

**Comment by shivank01** [comment]
I think we should setup Papers we love Bhubaneswar chapter #17  as it is quite different from others.

**Comment by hdidwania** [comment]
I think we can maintain a hierarchy for smooth functioning. Under TeSoc, we have two wings: the hardware and robotics wing- Technetronic, and the coding and software wing- PSoc. We both must collaborate and work together for smooth functioning as well as the improvement of Tech culture in college as a whole. Any other bodies, like some student chapter, can act as a supporting body to these wings. ACM can support coding wing in all of it events. And I guess hardware people are thinking to reactivate the IEEE student chapter of college too. Any other student chapter which we are able to set up, can support the two clubs and tesoc as a whole, and the perks and benefits availed by this chapter can be shared by the whole tech community of the college. 
Lets form a single body of us, a single body for tech. From there we can divide/recognize ourselves as part of different wing, and as someone responsible for a particular student chapter or SIG. This will help us work as a whole, as well as focus on specific bodies we represent.

**Comment by palash25** [comment]
> I think we should setup Papers we love Bhubaneswar chapter #17 as it is quite different from others.

@shivank01 would you be willing to lead that effort. I can help you with (founding the chapter) it whenever you want but I need someone to take the initiative. If you want to do it then keep me posted.

> I think we can maintain a hierarchy for smooth functioning. Under TeSoc, we have two wings: the hardware and robotics wing- Technetronic, and the coding and software wing- PSoc

Do we come under the tech society I thought we were independent and unrecognized? I used to think that technotronics and T-Soc are two separate official bodies recognized by the college and we are unofficial. @hdidwania

**Comment by shivank01** [comment]
@palash25  yeah I am ready to take the initiative to open the chapter.

**Comment by hdidwania** [comment]
There is nothing official in technetronic, as far as I understand. There is only one officially recognized club i.e. the tech society which receives all the funds from the college for the tech related stuff. Similarly, we PSoc, are not an official body as per the college and not completely independent, because as far as my understanding goes, we need to take funds from TeSoc for conducting events. 
I am suggesting that under this official umbrella body of TeSoc, let us have two independent bodies which work in collaboration with each other, as two separate wings, supported by various student chapters.

**Comment by arijeetsat** [comment]
Yeah that's a better idea ,in my opinion, we should take the benefits of all the chapters and collaboratively contribute to the tech culture of the college, since different chapters will have certain parameters to keep them active on a national level (i.e report submission, event summaries, annual awards etc.), that part can be taken care by the heads of those chapters.

**Comment by arijeetsat** [comment]
And the college can grow on all the platforms at all level collectively.
Resources + Activities +Outreach + National Recognititon  --->> Full Growth

**Comment by palash25** [comment]
> Resources + Activities +Outreach + National Recognititon --->> Full Growth

Very well put together :clap: @arijeetsat

**Comment by palash25** [comment]
If we can get enough technical writers this year then maybe we can start our own tech magazine.
I've seen IITR do it. Under their ACM they run an online magazine called Geek Gazette https://geekgazette.org/about/

**Comment by ankitjha97** [comment]
@palash25, @shivank01, @ayush1999, @arijeetsat, if you people want to be the part of ACM next session, you can make a team of approx 10 members by tomorrow and give the names to me so that I can forward it to Debashish Sir.
It can be good opportunity because you can organize events under the umbrella of ACM without worrying about funding and compete with other chapters.It's quite fun and with good team it's amazing.

**Comment by palash25** [comment]
I'm in favour of that I think we should conduct events under both ACM and the programming society

**Comment by ankitjha97** [comment]
Exactly, the main idea is to create an interactive and productive environment.ACM has many resources which can be properly utilized to organize diverse events.

**Comment by shivank01** [comment]
> @palash25, @shivank01, @ayush1999, @arijeetsat, if you people want to be the part of ACM next 

> session, you can make a team of approx 10 members by tomorrow and give the names to me so that I can forward it to Debashish Sir.
> It can be good opportunity because you can organize events under the umbrella of ACM without worrying about funding and compete with other chapters.It's quite fun and with good team it's amazing.

Ok.. We'll give you the list by tomorrow

**Comment by ayush1999** [comment]
I'm in.

**Comment by palash25** [comment]
Lets decide over here how many are in to be the part of the next ACM team.

I asked @knrt10 he is in (we need a webdev lead any way to build and maintain the ACM site)

@ayush1999 @shivank01 and I are in.

I think @arijeetsat would also like to be a part of the team (we would need his awesome management during all the events)

What about you folks @hdidwania @AbhiRepository @bkhanale @swap1108 @IamRaviTejaG  ?

**Comment by AbhiRepository** [comment]
Me too

**Comment by palash25** [comment]
> I am also a researcher as well, this year the management part is supposed to be a group task ,unlike last year. 

Duly noted. I wasn't aware about your interest in research too :sweat_smile: .

**Comment by sr6033** [comment]
Plan out and include those who will work actively.

**Comment by IamRaviTejaG** [comment]
I'm in too!

**Comment by ankitjha97** [comment]
By now, the team is:
@palash25 
@ayush1999  
@arijeetsat 
@shivank01 
@AbhiRepository 
@IamRaviTejaG

**Comment by ankitjha97** [comment]
@knrt10 is also there.
If anyone else wants to join, please write here.

**Comment by bkhanale** [comment]
I'm in too!

**Comment by palash25** [comment]
can someone ask @swap1108 too ?

**Comment by chiral-carbon** [comment]
I want to join!

**Comment by chiral-carbon** [comment]
Sorry for the delay, haven't been getting a good signal for the last few days

**Comment by palash25** [comment]
Now its 10 of us

**Comment by geekysrm** [comment]
I didn't see this earlier bros.
Count me in too. :)

**Comment by palash25** [comment]
11

**Comment by RajuKalidindi** [comment]
Count me in as well.
Sorry for the delay

**Comment by palash25** [comment]
12 I hope this is final now.

**Comment by gupta2140** [comment]
I'm in too. Sorry for the delay. Hadn't noticed this before.

**Comment by knrt10** [comment]
Lol maza aa rha hei. Now I waiting for PP's reply

**Comment by ankitjha97** [comment]
How many of you are part of other societies?
Since ACM and Programming Society will be collaborating together, I think it would be better to make sure that anyone of you is not over-burdened.
So please wisely put forward your names.

**Comment by palash25** [comment]
I think with the exception of 2 or 3 who have put forth their names all the rest are programming society members.
