### ISSUE TITLE
Online Presence

### ISSUE THREAD

**Issue by palash25** [p-society/goals#19]
- ~~A medium account to start a blog.~~
- ~~An official Twitter account for the programming society.~~
- ~~A LinkedIn page (mentioned as a not for profit organization)~~

Comment down with more ideas if you have any.

**Comment by debck** [comment]
I think creating a LinkedIn organisation would also be good ....

**Comment by palash25** [comment]
@debck I was just going to add that :smile: 
thanks for reminding me.

**Comment by debck** [comment]
😉😀😀

**Comment by palash25** [comment]
Done https://twitter.com/psociiit

**Comment by arijeetsat** [comment]
All Done, Closing this issue.
