### ISSUE TITLE
CLI for typeracer.com (https://github.com/p-society/typeracer-cli)

### ISSUE THREAD

**Issue by knrt10** [p-society/goals#20]
I am going to work on 1st project for p-society a CLI tool for http://play.typeracer.com/ . I am open to any suggestion. Implementation for local support won't be anything new cause online site is already there. So please suggest any idea how would you like to see it work in command line.

<blockquote><img src="http://typeracer-cdn.appspot.com/opensocial/images/TyperacerThumb64px.png" width="48" align="right"><div>TypeRacer</div><div><strong><a href="http://play.typeracer.com">TypeRacer - the global typing competition</a></strong></div><div>Race against live opponents typing quotes from books, movies, and songs.</div></blockquote>

**Comment by palash25** [comment]
How will you make this work?

Will it be completely offline? The paragraphs could be saved in a DB and the users can enjoy this offline practice mode

Online: Does typeracer have an API that we can use?

I would recommend you to go with both online (competitions) and offline (practice) modes.

I am also willing to develop it with you it sounds cool and I love cli tools.

**Comment by knrt10** [comment]
>I am also willing to develop it with you it sounds cool and I love cli tools
Always happy to work with you mah mayne.

**Comment by palash25** [comment]
Always leave a new line after a blockquote to separate the quoted text from your comment.

**Comment by knrt10** [comment]
As far as api is concerned we can make our own.

**Comment by knrt10** [comment]
Work started here
https://github.com/p-society/typeracer-cli

**Comment by palash25** [comment]
Since the MVP has been coded and implemented by @knrt10 we can close this now.
