### ISSUE TITLE
Nullptr on Telegram

### ISSUE THREAD

**Issue by palash25** [p-society/goals#21]
This could just be my opinion but I don't really like using whatsapp. I'm on my laptop most of the time and checking whatsapp everytime there is a message on nullptr is distracting.

Can we migrate to telegram, we can use it phone as well for quick communication whenever we are having sessions or meetings and it also has a desktop client which whatsapp doesn't have and whatsapp web sucks.

I need everyone's opinion on this cc @p-society/2019-batch @p-society/2020-batch

**Comment by shibasisp** [comment]
Yeah, telegram is great. It doesn't limit the number of users.Telegram bots can be built and is free unlike slack. However most people in our college don't use telegram and I am afraid they will not be active as they are active on WhatsApp. It will be hard to persuade people to move.
Let's try though!

**Comment by bkhanale** [comment]
Yes, telegram would be great!

**Comment by palash25** [comment]
If more than half of the members say yes to this we will migrate

**Comment by shivank01** [comment]
Yes,It would be great.

**Comment by hdidwania** [comment]
+1 in favor of migration from my side.

**Comment by ayush1999** [comment]
Yes!

**Comment by gupta2140** [comment]
Cool.

**Comment by IamRaviTejaG** [comment]
Yes, let's migrate to Telegram!

**Comment by nawedx** [comment]
Its late to vote but I would have voted yes.

**Comment by palash25** [comment]
This has been done already. Closing it.
