### ISSUE TITLE
CLI tool idea. Video---> Mp3

### ISSUE THREAD

**Issue by knrt10** [p-society/goals#33]
Just an idea. If anyone find this interesting please comment and also if anyone finds that there is already a CLI tool for that, then also please comment with link to that tool.

**Comment by IamRaviTejaG** [comment]
I assume you want to extract audio from a video file. **FFmpeg** gets the job done, and is extremely powerful. Infact, majority of the video converter softwares you find online use it for encoding, decoding, transcoding purposes. You can find all the relevant details here: https://www.ffmpeg.org/

If you intend to convert YouTube videos to audio, you can do it using **youtube-dl**. Find more info here: https://rg3.github.io/youtube-dl/. It also supports lot more services besides YouTube.

**Comment by knrt10** [comment]
Damm. Thanks, Closing this as this won't be useful.
