### ISSUE TITLE
HeatJam Online Programming Contest on CodeChef

### ISSUE THREAD

**Issue by bkhanale** [p-society/goals#34]
We have decided to conduct a new programming contest **HeatJam** on CodeChef in association with ACM Club and Programming Society. Currently, following people are assigned with the task:

Problem Setters: @ankitjha97 , @SamHenry97
Problem Tester/Admin: @bkhanale

Now, there are no prizes decided yet. I need to know if there is any need on including prizes provided the problems will be original and a very limited time will be provided comparing to the difficulty of the problems.

Also who will be funding the prizes (if decided) and also I would like to know the person preparing the posters and other stuff.

The date is not very fixed but we are expecting the contest to be in May itself.

**Comment by palash25** [comment]
For posters @IamRaviTejaG 

We need a few more designers and illustrators we can't dump all the work on Ravi.

@nayonika1999 @debck @sibasish14 @nebula001 you know anyone in the first year that is interested or has some experience with illustrator or photoshop

**Comment by nebula001** [comment]
Yes I know someone but have to ask him whether he will do or not.

**Comment by palash25** [comment]
Ask him and inform us on this thread

**Comment by nebula001** [comment]
Okay, will inform you soon.

**Comment by arijeetsat** [comment]
@bkhanale I think , lets not keep any prize for this contest for the time being. We can have prizes for later competitions.

**Comment by shivank01** [comment]
@bkhanale Can you ask codechef for ladoos for winner? if possible

**Comment by nebula001** [comment]
@legion3 can make the poster @palash25

**Comment by bkhanale** [comment]
@shivank01 The laddus depend upon the problems. If the problems are original and their editorials are well prepared and posted, they can issue laddus. Also, participation plays an important role. If there are not many participants they simply cannot issue laddus. 

This time we are preparing editorials along with the problems. But, the participation is something which we cannot control. I'll still request people at CodeChef to distribute few laddus among the winners.

**Comment by arijeetsat** [comment]
Participation depends on the domain of the competition, is the competition only for our college students??

**Comment by bkhanale** [comment]
@arijeetsat I'll be inviting some really good programmers for competition if the problems are good enough. I'm eagerly looking for my brother @abhishalya, he will give a good competition. He's in 9th grade and is doing far better in competitive programming. Also, he is a big open-source fan. He had participated in Google Code-in 2018. @palash25 maybe you can guide him a little.

**Comment by palash25** [comment]
> @palash25 maybe you can guide him a little.

@bkhanale sure I love to help people out with open source development but seeing that your brother has already participated in GCI I think he would already be familiar with it. Also, it is great to see a 9th grader get involved in competitive programming and OSS development. When I was his age all I knew was how to write a program to find out palindromes :laughing: 

If he needs any help you can tell him to ping me up on gitter or linkedin my username is the same as that of github.

**Comment by ankitjha97** [comment]
Hi guys. My phone charger is not working and since there is an election today in Karnataka,I couldn't buy one, and so I will be coordinating through this page only.
If there is any task for ACM or for me, then directly reply to this message.
@bkhanale, you can drop any message here.
@arijeetsat  , ask the ACM team for funding the competition.

**Comment by bkhanale** [comment]
@palash25 Sure, I will tell him about it. Also, you knew how to write a palindrome program when you were in 9th! At that age I wasn't having any idea on "programs" and palindrome would have been a totally strange word :P

**Comment by palash25** [comment]
> At that age I wasn't having any idea on "programs" and palindrome would have been a totally strange word :P

See how far you've come now. We can all learn from you.

**Comment by bkhanale** [comment]
@ankitjha97 I have your credentials. Give me your mail so that I can mail you those.

**Comment by ankitjha97** [comment]
ankitjhadelhi97@gmail.com

**Comment by bkhanale** [comment]
The contest page is created [here](https://www.codechef.com/HJ2018). Once the problems are ready we have to add them to the test page for testing purposes and for that we have to mail CodeChef. So, its better if we prepare the problems a bit before the expected time. Also, we need the editorial prepared along with the problem (The problem won't be added unless its editorial is prepared along with it). The problem setters can either comment here or can message me.

**Comment by bkhanale** [comment]
The prizes are confirmed by CodeChef:
1. Top 2 Participants: 250 laddus
2. Top 1 School Participant: 250 laddus
There are no cash prizes declared. 

One problem has been added to the test page by @Samhenry97. I would like to know the status of problems from others as well.

**Comment by arijeetsat** [comment]
Its good to have ladoos as the prize, great lead, have they demanded for any minimum number of participants?
And who else are the problem setters?

**Comment by arijeetsat** [comment]
Oh Yeah cool, so, we have to share about the competition in some other colleges as well. 
Which all colleges are you inviting people from?

**Comment by bkhanale** [comment]
I have few friends who might join us. But, majority participation is expected from our college itself. I don't have many contacts, so maybe you can help inviting people.

**Comment by arijeetsat** [comment]
Okay, we should start inviting people from other colleges, @palash25  @shivank01  please do share with all your contacts.

**Comment by palash25** [comment]
Done shared :+1:

**Comment by shivank01** [comment]
@bkhanale  I think we should share this on the college mail id

**Comment by arijeetsat** [comment]
Yup , go ahead ,send it to everyone. Also , I have shared in everywhere possible, still you do it. 👍

**Comment by bkhanale** [comment]
The contest is over. Unfortunately we did not get any good participation. We found that going for a closed contest isn't good enough. Hence, next time onward there would only be open contests. Also, we are again negotiating with CodeChef for revised status on the prizes. The winners will be mailed separately for the status on their prizes. Closing this issue now, no need of any further discussion.
