### ISSUE TITLE
New Logo

### ISSUE THREAD

**Issue by palash25** [p-society/goals#35]
@sr6033 on slack asked me to get someone to design a better logo. I kind of like our current one with the black background but suggestions for improvement or even the redesign of the current logo our welcome.

cc @IamRaviTejaG your thoughts?

![](http://res.cloudinary.com/dpft7mwni/image/upload/v1526060361/20953554_1954946628083395_1460884193752370788_n_lmbixc.jpg)

**Comment by IamRaviTejaG** [comment]
I'd suggest a redesign of the logo.

**Comment by palash25** [comment]
So @sr6033 wants us to get a professional to design our new logo. We would need to pay for that. I think if all of us chip in with a little money we can get this done. Anyone who wants to contribute comment on this thread. Let's also discuss possible designers for the logo over here. 

We should also integrate the Mozilla Campus Club logo into ours. ![](https://res.cloudinary.com/dpft7mwni/image/upload/v1526119289/poster-template-B-framed-1_ylsqox.jpg) ![](http://res.cloudinary.com/dpft7mwni/image/upload/v1526119290/poster-template-A-blue-1_ppmpz1.jpg)

cc @p-society/2019-batch @p-society/2020-batch

**Comment by arijeetsat** [comment]
How much amount will be needed? And do we really need professional designer, all our college poster were designed by college students only at the time of Advaita.

**Comment by palash25** [comment]
@sr6033 asked me to get professional help for the logo on slack. But if a student comes up with a really good design I think that would be great.

**Comment by hdidwania** [comment]
Is it necessary to integrate mozilla campus club logo with it? (I mean to ask does mozilla expects/asks us to do so?)

Think from my perspective, we are P-Soc, the programming club of IIIT-Bh. P-Soc is our identity. We can say that we partnered with mozilla campus clubs, or ACM Student Chapter, or any other chapters/body we open in future, for perks and benefits. Like these bodies are sort of supporting body to PSoc, right? I want us and others to recognize ourselves as P-Soc, an entity of our own. We are not ACM IIIT Bh, we are not Mozilla IIIT Bh, not primarily, we are P-Soc, right? That's my perspective. I want that we remain primarily as P-Soc. Yes, we should try to get help from as many bodies as possible, ACM, Mozilla, IEEE, etc, but when its done and all, we recognize ourselves as P-Soc. And hence I would go against the idea of integrating mozilla campus club's logo with P-Soc logo.

**Comment by arijeetsat** [comment]
Good point by @hdidwania and I completely agree with that , even if we are integrating with Mozilla Club , keep it as another part, and lets keep the identity of P-Soc . In the long run ,its important to have unique society of our college. We may be submitting reports to ACM or Mozilla ,that can be formulated easily, but lets keep P-Soc as individual body.

**Comment by palash25** [comment]
> are not Mozilla IIIT Bh, not primarily, we are P-Soc, right?

We kind of are now. But its okay if you dont want the Mozilla logo integrated with ours that was just an idea. I don't think its compulsory for mozilla campus clubs to change their logo. 

I'm going to wait for other people to comment on logo ideas and see where it takes us. In the end the decision will be unanimous.

**Comment by palash25** [comment]
Maybe we can have our own unique p-soc logo along with it at the bottom we can write. 
**Programming Society IIIT-Bh**
    *A Mozilla Campus Club*

**Comment by hdidwania** [comment]
> Maybe we can have our own unique p-soc logo along with it at the bottom we can write.
> Programming Society IIIT-Bh
> A Mozilla Campus Club

Yes, we can do this.

**Comment by shivank01** [comment]
@palash25 @arijeetsat @hdidwania We can also contact uttariyo saha(etc or eee branch). He is a professional logo designer. May be he can help us in this.

**Comment by arijeetsat** [comment]
Yup, lets see if we can get some contacts with other students as well.

**Comment by palash25** [comment]
Can someone contact him or he is on Github can someone invite him to be a part of the discussion on this thread?

**Comment by IamRaviTejaG** [comment]
@palash25 @arijeetsat @hdidwania @shivank01 

We can contact Soumya Ranjan Bishi bhaiya. He's an alumni and is a professional designer. Advaita's logo (VA) is his design. I'll contact him regarding the P-Society logo. Will be posting updates here.

**Comment by sr6033** [comment]
I can talk with him. I am working with him here in param. But we are a lot busy. I don't think he can find out time.

**Comment by IamRaviTejaG** [comment]
@sr6033 Please talk to him and try your best to convince him. He is really really good at designing, so we can expect a really good logo design from him.

**Comment by knrt10** [comment]
Whatever decision you all make I am cool with that.

**Comment by arijeetsat** [comment]
For the new logo , I have talked to Manish Ray of CE , he is very proficient at this, in some days he will be giving us some sample, lets wait for it. 👍

**Comment by palash25** [comment]
Any updates @arijeetsat ?

**Comment by arijeetsat** [comment]
Will contact him again, any specific idea you people want in the logo?

**Comment by palash25** [comment]
It has been already discussed on this thread

**Comment by arijeetsat** [comment]
Nothing about the design is mentioned, I mean does anybody have any particular design thing in mind like what shape/image should be there, that has to be added?

**Comment by palash25** [comment]
I don't but one thing you can do is give the guy these two images that have been posted and tell him to take inspiration from those.

**Comment by nawedx** [comment]
Shape of the logo: Something that can fit into a circle of square
Design style : Cartoony/Doodly, Colorful

**Comment by Ashugupta01** [comment]
Can someone throw up any more suggestions for the logo? Maybe I can whip up one..

**Comment by palash25** [comment]
@p-society/2019-batch @p-society/2020-batch :point_up:

**Comment by palash25** [comment]
> Can someone throw up any more suggestions for the logo? Maybe I can whip up one..

Read the whole thread and discuss your design on this thread :+1:  @Ashugupta01

**Comment by Ashugupta01** [comment]
okay...

**Comment by palash25** [comment]
I don't see any progress from @Ashugupta01 on this and @sr6033 has already shown us a glimpse of the new logo so I am closing this in favour of that

@Ashugupta01 sorry about this but if you are interested in working with us there will be a lot more opportunities to work with us. Like designing posters for our upcoming sessions or Advaita. 

If you are interested in any such work DM me on slack around August :+1:
