### ISSUE TITLE
PORs for Upcoming Session

### ISSUE THREAD

**Issue by ankitjha97** [p-society/goals#39]
@palash25 @arijeetsat @IamRaviTejaG @nawedx @chiral-carbon @bkhanale @shivank01 @knrt10 @gupta2140 @ayush1999 @geekysrm , check it out.

**ACM Team**:

_Treasurer_ - Abhipsha
_Chairman_ - Arijeet
_Vice Chairman_- Bhushan
_Secretary_ - Shivank
_Web Master_ - Kautilya
_Competitive Programming  Lead_ - Bhushan
_Open source Lead_ - Aman Gupta
_Data Science Lead_ - Ayush Sridhar
_Web Team Lead_ - Soumya Ranjan

**Psoc Heads** - Palash and Nawed
**Tech. Secretary** - Arijeet
**Mozilla Club** - Palash and Ravi Teja

**Comment by ankitjha97** [comment]
The decision has been taken by internal discussion between the previous PORs of ACM and Psociety.The PORs have been decided by considering each one of you's participation in the previous session and some others who couldn't be a part of the list can join as a member because it is the will to work which matters the most.

**Comment by ankitjha97** [comment]
I wish each one of **All The Best** and you all are equally capable so make the best use of your tenure.

**Comment by arijeetsat** [comment]
Great team all together ,including those not mentioned here, It's gonna be the best year for Tech. Of IIIT-Bh, all will be working together, supporting others, and thats the way its going to be achieved. All the Best to this year team!!!😊😊💐👌
