### ISSUE TITLE
Turn p-society into a Mozilla campus club

### ISSUE THREAD

**Issue by palash25** [p-society/goals#4]
This is a work in progress and I am in talks with Mozilla.

People responsible @palash25 and @iamravitejag

**Comment by palash25** [comment]
Programming society is now a Mozilla Campus Club. :tada: ![](https://res.cloudinary.com/dpft7mwni/image/upload/v1526046705/campusclubs_zfrclx.png)

I am the club captain and @IamRaviTejaG is my co-captain. This doesn't introduce some kind of hierarchy in our club and we will work together, the same way as we used to before. This only means that @IamRaviTejaG and I will be responsible for keeping Mozilla updated of our activities.

They are in the process of updating their site so it might take a while before we see our society's name up there. I will keep you folks posted.

Now all our future activities will be conducted under the Mozilla and ACM banner.

Have some :cake: 

cc @p-society/2019-batch @p-society/2020-batch

**Comment by knrt10** [comment]
Yippe.. thats so messi and ronaldo!!!

**Comment by palash25** [comment]
Closing this. Thank you all for your appreciation :smile:
