### ISSUE TITLE
IIIT complaint portal

### ISSUE THREAD

**Issue by geekysrm** [p-society/goals#48]
I am facing some problems in the college(read shitty internet) and I realized I have no where to go online to complain about it. 
Other colleges have their own complaint portals:
IIIT KGP: http://www.hmc.iitkgp.ac.in/gportal/
BITS PILANI(Goa campus): http://csatimes.co.in/2016/08/04/hostel-room-complaint-goes-online/

etc.

Maybe our college has such a portal and I am unaware of it please let me know.
Otherwise, I would start working on making one.

<blockquote><div><strong><a href="http://www.hmc.iitkgp.ac.in/gportal/">Students' Complaint Portal | Indian Institute of Technology Kharagpur</a></strong></div></blockquote>
<blockquote><img src="https://i0.wp.com/csatimes.co.in/wp-content/uploads/2017/01/cropped-300px-BITS_Pilani-Logo.svg_.png?fit=512%2C512" width="48" align="right"><div><img src="https://i0.wp.com/csatimes.co.in/wp-content/uploads/2017/01/cropped-300px-BITS_Pilani-Logo.svg_.png?fit=192%2C192" height="14"> CSA TIMES</div><div><strong><a href="http://csatimes.co.in/2016/08/04/hostel-room-complaint-goes-online/">Hostel Room Complaint Goes Online</a></strong></div><div>Computer Center launches new Compliant management system for more info visit 10.1.1.54.   Any student from any hostel may log in in to the ‘complain management system’ of the Insti…</div></blockquote>

**Comment by palash25** [comment]
@arijeetsat @shivank01 any idea about this? If not maybe @geekysrm can build one. Another project for p-soc

**Comment by arijeetsat** [comment]
Thank you @geekysrm for opening up this issue, i have once discussed this with @shivank01. Instead of naming it as complaints portal , let's name it as a forum, which will have different sections , where people can share their opinions, expectations from college authority or different clubs, also they can maintain their anonymity (if they want to). If the concerns regards the club activities then the secretaries can answer, if it's beyond that ,then a poll or something can be noted for administrative use. Forum will help any random person to get a reply from the moderators.The moderator can also manage any abusive or inappropriate content posted on the forum.

**Comment by arijeetsat** [comment]
Can be clubbed up with #issue3

**Comment by sonu12485** [comment]
Facing the same internet problem.
Good idea.
Very much needed.

**Comment by shivank01** [comment]
Yeah, We should build one. But if there is anonymity then someone may post shitty questions and feedbacks. Like the one in the last year "the tech society feedback google form".

**Comment by arijeetsat** [comment]
It's ok , the moderator will manage that , anonymity is needed.

**Comment by adityaprakash-bobby** [comment]
This can be one example : http://forum.iiit.ac.in/2017/?page_id=14

<blockquote><img src="http://forum.iiit.ac.in/2017/wp-content/themes/twentyten/favicon.ico" width="48" align="right"><div><strong><a href="http://forum.iiit.ac.in/2017/?page_id=14">Forums | IIIT-H Admission Forum</a></strong></div></blockquote>

**Comment by geekysrm** [comment]
Just created a new repo, and will start working on it.
https://github.com/p-society/IIIT-forum

<blockquote><img src="https://avatars1.githubusercontent.com/u/29895434?s=400&v=4" width="48" align="right"><div><img src="https://assets-cdn.github.com/favicon.ico" height="14"> GitHub</div><div><strong><a href="https://github.com/p-society/IIIT-forum">p-society/IIIT-forum</a></strong></div><div>IIIT-forum - Repository for IIIT Forum [WIP]</div></blockquote>
