### ISSUE TITLE
Become a Google DSC(Developer Student Club)

### ISSUE THREAD

**Issue by dnabanita7** [p-society/goals#50]
What is the benefit of being a DSC lead?

- Grow your personal and professional network
- Lead a Google developer community
- Help students grow as developers
- Build real-life solutions to local problems in your community.
- Get access to Google Developers' resources and opportunities
- Be part of Google's Developer Ecosystem- https://developers.google.com/programs/
- Participate in a global Solution Challenge
- Participate in Google Conferences and a DSC Summit

What are the application acceptance requirements to become a DSC lead?

- Enrolled in an undergraduate program at a college or university.
- Have minimum two years left until graduation.
- Passionate about creating impact in your community.
- Strong technical understanding of computer programming and/or software engineering.
- Have experience leading a team. This may include experience leading members or an
         organizing team with a student club, charitable cause, school project (does not need to be related to technology).

What type of commitment is needed as a DSC lead?

- Participation during one full academic year and mentor the second
- Set up or grow existing Developer Student Club within respective campus;
- Attendance at one 2-3 day onboarding summit in your region.
- Join one hour or less bi-weekly or monthly calls with Googlers to check-in and ask questions.
- Organize and host hands on workshops
- Identify local organizations and businesses who would benefit from technology based 
  solutions and facilitate project based problem solving activities for club members
- Host showcase events that celebrate and build awareness around the projects built by your community.
- Share information about club activities through simple post-activity reporting form.
- On-board and pass off ownership to the next years DSC Lead for your community.

**Who can apply?**

A student that is currently enrolled between the 2nd — penultimate year in a computer science course or related engineering discipline at any accredited college/university

DSC is a Google Developers program for University students, designed to help you build your mobile and web development skills and knowledge.

It is open to any student, ranging from novice (developers who are just starting), to advanced (developers who want to further improve their skills). The intention is for you to learn and collaborate as you solve mobile and web development problems for local businesses in your region.

@p-society/2022-batch 
The application form for India is open from March-April iirc, please apply for it. 

<blockquote><img src="https://www.gstatic.com/devrel-devsite/v45ff8f523b59dba1a68309c845322ac9e5fdaa00274f34f2986d46556e823992/developers/images/favicon.png" width="48" align="right"><div>Google Developers</div><div><strong><a href="https://developers.google.com/community">Learn about our Developer community programs  |  Google Developers</a></strong></div><div>Find, connect, build. Join a developer community today.
</div></blockquote>

**Comment by debck** [comment]
@Naba7  I think we already have a DSC chapter in our college. 
Hardik Singh Bhaiya is the lead.

**Comment by arijeetsat** [comment]
Yup Contact Hardik and transfer the lead before the end of this year, Siddharth of EEE 2nd Yr is very active with the DSC lead, contact him and help him manage the activities.

**Comment by dnabanita7** [comment]
Yes, I know that. But we need an active lead for upcoming years.@debck 
Alright then. I will talk to him. @arijeetsat 
Closing this for now.
