### ISSUE TITLE
Discussion Regarding Recruitment of First-Year Students (2027 Batch) 

### ISSUE THREAD

**Issue by zakhaev26** [p-society/goals#54]
We will be inviting first-year students to join PSoc most probably after the summer break. We want to make sure these projects are easy for beginners but still interesting and helpful so that on the basis of these tasks/their progress we can recruit only the hardworking and best talents from the batch.

These projects should be easy enough for beginners to understand and do.

> [!IMPORTANT]  
 > ## Criteria For Ideas
 > Should be easy-to-medium for beginners.
    Aren't too hard, but still teach something new.

### Instructions for Domain Leads:
If you're a domain lead, please think of simple - yet learning projects that first-year students can do. When you suggest a project, tell us what it's about, what skills are needed, and how hard it is.

## When you share your project idea, please include:

    - Project Title
    - Domain
    - Description 
    - Skills Needed
    - Difficulty Level
    - ETA

> [!WARNING]  
 > Refrain from using AI Tools to generate your answers.
 > Share your ideas STRICTLY in this issue thread,or discuss in the [Discord channel of PSoc](https://discord.gg/D9JVgcmBae),

Other than this,even if you are not a Domain Lead,feel free to be a part of the discussion and suggest ideas!

CC: @majorbruteforce @punitkr03 @Divyakumar21202  (Will tag more ASAP)

**Comment by majorbruteforce** [comment]
You may use this:

[Project Title]

Description:
 Briefly describe what the project is about, what it solves and some general use cases.

Features: 
- State clearly the things that the project aims to achieve
- Describe briefly what each feature 
- Keep it crisp and to-the-point

Tech to learn: 
- Mention programming languages and frameworks that might be used to achieve it
- Provide a road map on how they can go through them
- Provide resources that you deem useful
- Keep in mind that these should be for easy to medium projects

Best practices: 
- Mention developer practices that one must adhere to while learning for the project and developing it
- Provide resources to learn these

**Comment by Ehtisham9198** [comment]
Hoping that everyone is working on recruitment task, if you have any query, you can share here

**Comment by zakhaev26** [comment]
yup,thinking about some ideas on web,will put them up here asap

**Comment by venkat2295** [comment]
Task 
https://docs.google.com/document/d/1xavYJc3e9fNozkDJPRVjuxqG93KewhUbXolne9jiRv8/edit?usp=sharing

**Comment by zakhaev26** [comment]
<a href="https://docs.google.com/document/d/1bU7kbXD-uxZn-vM4CLh3mQMGeAdDaspYTT4LDreb6wQ/edit">A Log analysis cli tool , implementing heavy use of Data Structures,Algorithms and backend</a>

**Comment by Shikha1601** [comment]
https://docs.google.com/document/d/1jdrTr6ly-ASgOdV2EZ_kWU-d5d7A8sXopEIHsuIGXAA/edit?usp=sharing

**Comment by anshumanverse** [comment]
https://docs.google.com/document/d/1M-qgZEE9DlSnnIAEUVWoUjltQRRWaWR-9AiiNsaTXjU/edit?usp=drivesdk

for management recruitment

**Comment by zakhaev26** [comment]
Thanks everyone for showing a collaborative effort.
@majorbruteforce is in the process of compiling all these docs - this will be shared to undergrads once everything is set up.
GGWP
Closing #54 as completed.
