### ISSUE TITLE
Idea: Discord Bot for Student Monitoring during 45 Days of Code

### ISSUE THREAD

**Issue by zakhaev26** [p-society/goals#55]
How about developing a discord bot to ease the monitoring process and improve the experience for participants of the 45 Days of Code program? We have time till 1st June 2023 

Currently, managing student logs, task completion statuses, and message activity over excel sheets relies on manual processes will be cumbersome and this proposed bot will automate these tasks, allowing students to log their daily progress, mark tasks as completed, and engage in discussions within designated channels. 

Administrators will have access to a dashboard for managing logs and tracking overall program engagement. 

CC: @majorbruteforce @punitkr03 @ehtisham9198

**Comment by majorbruteforce** [comment]
Yup it will be fun and will also streamline yhe process. Let's do it 🤖

**Comment by punitkr03** [comment]
I was thinking of the same, let's do it.

**Comment by zakhaev26** [comment]
As the MVP idea was built ,tested and used in the production too, this was a job well done..!
Closing this as completed.
