### ISSUE TITLE
P-Soc FOSS Wing Site

### ISSUE THREAD

**Issue by palash25** [p-society/goals#7]
Our little club has a lot of open source contributors and I was thinking about having a little site dedicated to all the open source activities.

A list of all the open source developers from the college.
A list of all the projects/orgs that all the stuednts have contributed to so far.
A list of conferences that the students went to or gave a talk at.
SOC or WOC programmes that the students have participated in.

Follow the below link.

http://openhub.net/

<blockquote><div><strong><a href="http://openhub.net/">Open Hub, the open source network</a></strong></div></blockquote>

**Comment by knrt10** [comment]
Lets roll with it. Let's discuss the implementation.

**Comment by knrt10** [comment]
http://openhub.net/

**Comment by knrt10** [comment]
http://openhub.net/

**Comment by knrt10** [comment]
http://openhub.net/

**Comment by palash25** [comment]
Lets do that after failing in TOC :laughing:

**Comment by palash25** [comment]
You can start discussing it just comment below if you want.

**Comment by sr6033** [comment]
Also get in touch with linuxday.org. I was in contact with them last year to organise a linux devfest under their banner in college. It was not implemented but u can try this year.

**Comment by palash25** [comment]
Will do for sure.

**Comment by knrt10** [comment]
@IamRaviTejaG would you please make a 16by16 icon for p-society website.

**Comment by knrt10** [comment]
closing this as its implemented in github.com/p-society/p-society.github.io
