### ISSUE TITLE
Creation of SIGs

### ISSUE THREAD

**Issue by palash25** [p-society/goals#8]
We need to create special interests groups within our organization. Originally suggested by sudoankit when he talked to us during the first meeting of the programming society.

**Comment by hdidwania** [comment]
Much required. In this way we can divide ourselves to specifically focus on some particular topics. Will also be a great way for conducting smooth discussions/sessions

**Comment by palash25** [comment]
I think this has already started with the creation of the aerial UAV sig, so this can be closed
